description = "thin-edge.io default recipes"
dependencies = [
    "core/persist-root-home",
    "rugix-extra/zsh",

    "essentials",
    "persist-network-manager",
    "set-wifi",
    "rugix-extra/simple-sbom",
    "ssh",
]