#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "Set wifi access"

[parameters]
id = { default = "wifi" }
ssid = { default = "" }
password = { default = "" }
country_code = { default = "DE" }
