#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "Add workflow scripts to support firmware updates"
dependencies = [
    "core/pkg-update",
    "thin-edge.io",
]

[parameters]
autorollback = { default = true }
