#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-recipe.schema.json
description = "setup network"
# Run early to prevent resolve conf issues during building
priority = 200_000
dependencies = [
    "core/pkg-update",
]
