#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-recipe.schema.json
description = "ssh authorized keys using config or env variables SSH_KEYS_.*"
dependencies = ["core/ssh"]

[parameters]
root_authorized_keys = { default = "" }

# CSV list of GitHub usernames to retrieve their public ssh keys from
# to be appended to root's authorized keys, e.g. myuser,foo,bar
# The keys are retrieved from the public URL: https://github.com/<user>.keys
root_authorized_keys_github_users = { default = "" }
