#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "ssh authorized keys using config or env variables SSH_KEYS_.*"
dependencies = ["core/ssh"]

[parameters]
root_authorized_keys = { default = "" }
