#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "install podman"
priority = 10_000

dependencies = [
    "tedge-community-repo",
]
