#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-layer.schema.json
parent = "debian-trixie"

recipes = [
    # default tedge packages
    "defaults",

    # Setup the network
    "setup-network",
]