#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-layer.schema.json
parent = "raspios"

recipes = [
    "core/rpi-raspios-setup",
    "defaults",

    # SBOM
    "rugix-extra/simple-sbom",
]