#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-layer.schema.json
parent = "raspios"

recipes = [
    "core/rpi-raspios-setup",
    "defaults",
    "raspi-tpm",
    "setup-pkcs11",

    # use avahi instead of systemd-resolved due to
    # an issue with high cpu usage
    "avahi-daemon",

    # containers
    # NOTE: docker has an issue building on armhf (suspected debian target arch mismatch)
    # which results in the installed binary running into a segmentation fault when run
    # however installing at runtime works.
    # "docker",

    # Include u-boot setup on all image
    # to avoid having to create a layer per-bootloader
    # and it does not cause any negative effects
    # including it for tryboot
    "core/rpi-uboot-setup",

    # SBOM
    "rugix-extra/simple-sbom",
]

# exclude specific recipes which are currently not supported on older versions
# due to various issues
exclude = [
    # high cpu usage on rpi1
    "systemd-resolved",
]
