#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-layer.schema.json
parent = "core/debian-bookworm"

recipes = [
    # default tedge packages
    "defaults",

    # containers
    "docker",

    # Setup the network
    "setup-network",

    # PKCS11 tools
    "setup-pkcs11",

    # SBOM
    "rugix-extra/simple-sbom",
]