#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-layer.schema.json
parent = "raspios"

recipes = [
    "core/rpi-raspios-setup",
    "defaults",
    "raspi-tpm",
    "setup-pkcs11",

    # use avahi instead of systemd-resolved due to
    # an issue with high cpu usage
    "avahi-daemon",

    # containers
    # use podman as docker has deprecated support for Raspberry OS and 
    # armhf (armv6) images, see https://docs.docker.com/engine/install/raspberry-pi-os/
    "podman",

    # Include u-boot setup on all image
    # to avoid having to create a layer per-bootloader
    # and it does not cause any negative effects
    # including it for tryboot
    "core/rpi-uboot-setup",

    # SBOM
    "rugix-extra/simple-sbom",
]

# exclude specific recipes which are currently not supported on older versions
# due to various issues
exclude = [
    # high cpu usage on rpi1
    "systemd-resolved",
]
