#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-layer.schema.json
parent = "core/debian-bookworm"

recipes = [
    # default tedge packages
    "defaults",

    # Setup the network
    "setup-network",

    # PKCS11 tools
    "setup-pkcs11",

    # SBOM
    "rugix-extra/simple-sbom",
]