#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-layer.schema.json
parent = "raspios"

recipes = [
    "core/rpi-raspios-setup",
    "defaults",
    "raspi-tpm",
    "raspi-i2c",
    "setup-pkcs11",

    # containers
    "docker",

    # Include u-boot setup on all image
    # to avoid having to create a layer per-bootloader
    # and it does not cause any negative effects
    # including it for tryboot
    "core/rpi-uboot-setup",

    # SBOM
    "rugix-extra/simple-sbom",
]