#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-layer.schema.json
parent = "tedge-debian-12"

recipes = [
    # Setup Debian for booting via Grub.
    "core/debian-grub-setup",
]