#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "Sensible cmdline.txt options, e.g. enable cgroups monitoring"
priority = 500_000  # Execute rather early to allow recipes to modify it
