#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-recipe.schema.json
description = "Configure thin-edge.io tedge-dev Repository"
priority = 110_000

dependencies = [
    "core/pkg-update",
]