[[files]]
path = "/etc/tedge/tedge.toml"
type = "tedge.toml"

[[files]]
path = "/etc/mosquitto/conf.d/tedge-mosquitto.conf"
type = "tedge-mosquitto.conf"
service = "mosquitto"

[[files]]
path = "/etc/tedge/plugins/tedge-log-plugin.toml"
type = "tedge-log-plugin"
user = "tedge"
group = "tedge"
mode = 0o0644

[[files]]
path = "/etc/tedge/plugins/.netrc"
type = "netrc"
user = "tedge"
group = "tedge"
mode = 0o0660
