name = "deployment-check"
version = "1.0.9"

[input.process]
topic = "deployments/${params.group}/rollout"
command = """/etc/tedge/mappers/c8y/flows/deployment-check/check-deployment.sh ${params.group} --version ${params.version}"""
interval = "${params.interval}"

[config]
group = "${params.group}"
version = "${params.version}"

[[steps]]
script = "main.js"
