#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-recipe.schema.json
description = "zero touch provisioning"
dependencies = [
    "core/pkg-update",
    "tedge-community-repo",
]