#!/bin/sh
##################################################
# Parse firmware file marker
#
# Example file contents:
# ```
# {
#   "name": "tedge-debian-12-efi-arm64",
#   "release": {
#     "id": "tedge-debian-12-efi-arm64",
#     "version": "20250308.1219"
#   }
# }
##################################################
set -e
ARTIFACT_FILE=/etc/rugix/system-build-info.json

if [ ! -f "$ARTIFACT_FILE" ]; then
    exit 0
fi

NAME=$(jq -r '.name' "$ARTIFACT_FILE")
VERSION=$(jq -r '.release.version // "0.0"' "$ARTIFACT_FILE")

echo "name=\"$NAME\""
echo "version=\"$VERSION\""
