#!/bin/sh
set -e

SUDO=""
if command -V sudo >/dev/null 2>&1; then
    SUDO="sudo"
fi

RUGIX_INFO=$($SUDO rugix-ctrl system info ||:)
HOT=$(echo "$RUGIX_INFO" | grep Hot | cut -d: -f2 | xargs)
DEFAULT=$(echo "$RUGIX_INFO" | grep Default | cut -d: -f2 | xargs)

if [ -n "$HOT" ] && [ -n "$DEFAULT" ] && [ "$HOT" = "$DEFAULT" ]; then
    echo "Already on default partition. Nothing to rollback to. hot=$HOT, default=$DEFAULT" >&2
    exit 0
fi

echo "Rebooting into default partition. hot=$HOT, default=$DEFAULT"
reboot
exit 0
