description = "Enable tpm device tree overlay tpm-slb9670"
dependencies = [
    "core/pkg-update",
    "thin-edge.io",
    "tedge-community-repo",
]

[parameters]
tss_user_id = { default = "112" }
tss_group_id = { default = "112" }
