persistence true
persistence_location /var/lib/mosquitto/
log_dest syslog

# increase default size (which is 20) to avoid problems where messages can be
# silently dropped
max_inflight_messages 200

include_dir /etc/tedge/mosquitto-conf
include_dir /etc/mosquitto/conf.d