#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-recipe.schema.json
description = "Work-in-progress - install k3s"
dependencies = [
    "core/pkg-update",
]