#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "Enable MQTT logger to help with debugging issues"

[parameters]
enable_service = { default = "true" }
