#:schema https://raw.githubusercontent.com/rugix/rugix-bakery/refs/tags/v0.9.0/schemas/rugix-bakery-recipe.schema.json
description = "Enable MQTT logger to help with debugging issues"

[parameters]
enable_service = { default = "true" }
