#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "install state file for `/data`"
priority = 600_000  # Execute rather early.
