#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "Work-in-progress - Parsec (only supported on Debian Trixie)"
priority = 10_000
